
name: stage-tests

on:
  push:
    branches: [stage]

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Working Action
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -r requirements.txt
        pip install ruff
    - name: Run linting
      run: |
        ruff check pyhydrate/ tests/
    - name: Run formatting
      run: |
        ruff format --check pyhydrate/ tests/
    - name: Run tests
      run: |
        python -m unittest discover -s tests/ -p "*_tests.py"
