name: CD

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  RELEASE_VERSION: ${{ github.event.release.tag_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Working Action
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install setuptools
        pip install wheel
        pip install toml
        pip install -r requirements.txt
    - name: Update Release Version
      run: |
        python -c """
        import toml
        import os

        _ver = os.environ.get('RELEASE_VERSION', 'v0.0.0')

        with open('pyproject.toml', 'r') as f:
            config = toml.load(f)
            config['project']['version'] = _ver.strip('v')
        
        with open('pyproject.toml', 'w') as f:
            toml.dump(config, f)
            print(f"Project Version updated to {_ver} in pyproject.toml file.")
        """
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
